# NLP Zero to Hero

## Introduction to NLP

Natural Language Processing (NLP) is a sub-field of artificial intelligence (AI) that focuses on the interaction between computers and humans through natural language. The ultimate objective of NLP is to enable computers to understand, interpret, and generate human languages in a way that is both meaningful and useful.

### Why is NLP Important?

NLP is important because it helps resolve ambiguity in language and adds useful numeric representation to the data for many downstream applications, such as text analytics or speech recognition. Here are some reasons why NLP is important:

1. **Volume of Text Data**: With the explosion of digital communication, the amount of text data generated daily is vast. NLP helps in extracting useful information from this vast amount of unstructured data.
2. **Human-Computer Interaction**: NLP provides more natural interactions between humans and computers, making technologies like virtual assistants and chatbots more effective.
3. **Automation of Routine Tasks**: NLP can automate and align routine tasks such as summarizing documents, filtering spam emails, and translating languages.

### Applications of NLP

NLP has a wide range of applications across various domains:

- **Text Classification**: Categorizing text into predefined categories. For example, filtering spam emails or classifying customer reviews.
- **Sentiment Analysis**: Determining the sentiment expressed in a piece of text, such as identifying positive or negative reviews.
- **Machine Translation**: Translating text from one language to another, like Google Translate.
- **Named Entity Recognition (NER)**: Identifying entities such as names, dates, and places within a text.
- **Speech Recognition**: Converting spoken language into text, as used in virtual assistants like Siri and Alexa.
- **Chatbots**: Enabling conversational agents to understand and respond to human queries in real-time.
- **Text Summarization**: Creating a summary of a longer piece of text.


### Basic NLP Concepts and Terminology

Before looking into NLP tasks, it's essential to understand some basic concepts and terminology:

- **Tokenization**: The process of splitting text into individual words or phrases, known as tokens.
- **Stopwords**: Common words like "the", "is", "in", which are often removed from text before processing because they add little value to the analysis.
- **Stemming and Lemmatization**: Techniques to reduce words to their base or root form. Stemming is a crude heuristic process that chops off the ends of words, while lemmatization uses a dictionary to find the root form.
- **Vectorization**: Converting text into numerical format. Common methods include Bag of Words (BoW) and Term Frequency-Inverse Document Frequency (TF-IDF).
- **Word Embeddings**: Dense vector representations of words, capturing their meanings, semantic relationships, and context. Examples include Word2Vec, GloVe, and FastText.
- **Sequence Models**: Models like Recurrent Neural Networks (RNNs), Long Short-Term Memory (LSTM), and Gated Recurrent Units (GRUs) that are capable of processing sequences of data.
- **Transformers**: A type of model architecture that has revolutionized NLP, particularly through models like BERT, GPT, and T5. Transformers handle sequences in parallel and have shown significant improvements in various NLP tasks.

### Structure of This Notebook

This notebook will take you through a journey from basic NLP tasks to more advanced techniques. Here’s the structure:

1. **Text Preprocessing**
   - Tokenization
   - Stopword removal
   - Stemming and Lemmatization
   - Vectorization

2. **Basic NLP Tasks**
   - Sentiment Analysis
   - Named Entity Recognition (NER)
   - Part-of-Speech Tagging
   - Text Classification

3. **Advanced NLP Techniques**
   - Word Embeddings (Word2Vec, GloVe)
   - Sequence Models (RNN, LSTM, GRU)
   - Attention Mechanisms and Transformers
   - BERT and other Transformer-based models

4. **Practical Projects**
   - Building a Sentiment Analysis Model
   - Creating a Chatbot
   - Text Summarization
   - Machine Translation

5. **Conclusion and Further Reading**
   - Summary of key points
   - Resources for further learning

Let's get started on this exciting journey into the world of Natural Language Processing!

# Part 1 : Text Preprocessing

### 📝 Importing libraries

In [38]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import spacy

#### 🚀 Let's download NLTK and Spacy data we need (just once)

In [39]:
!python -m spacy download en_core_web_md

  Using cached https://github.com/explosion/spacy-models/releases/download/en_core_web_md-3.7.1/en_core_web_md-3.7.1-py3-none-any.whl (42.8 MB)
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_md')


In [40]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nlp = spacy.load('en_core_web_sm')
# nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to /usr/share/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /usr/share/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /usr/share/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [41]:
# 🌟 Example text
text = """
FeatureLens generates visuals by applying text mining concepts such as frequent words, expressions, and closed itemsets of n-grams to guide the discovery process. These concepts are combined with interactive visualization to help users analyze text, create insights
"""

### 🪄 Step 1: Tokenization - Breaking text into words (tokens) 🌟

In [42]:
tokens = word_tokenize(text)
print("🔹 Tokens:", tokens)

🔹 Tokens: ['FeatureLens', 'generates', 'visuals', 'by', 'applying', 'text', 'mining', 'concepts', 'such', 'as', 'frequent', 'words', ',', 'expressions', ',', 'and', 'closed', 'itemsets', 'of', 'n-grams', 'to', 'guide', 'the', 'discovery', 'process', '.', 'These', 'concepts', 'are', 'combined', 'with', 'interactive', 'visualization', 'to', 'help', 'users', 'analyze', 'text', ',', 'create', 'insights']


### 🛑 Step 2: Stopword removal - Get rid of those pesky common words 🛑

In [43]:

stop_words = set(stopwords.words('english'))
filtered_tokens = [word for word in tokens if word.lower() not in stop_words]
print("🔹 Tokens after stopword removal:", filtered_tokens)


🔹 Tokens after stopword removal: ['FeatureLens', 'generates', 'visuals', 'applying', 'text', 'mining', 'concepts', 'frequent', 'words', ',', 'expressions', ',', 'closed', 'itemsets', 'n-grams', 'guide', 'discovery', 'process', '.', 'concepts', 'combined', 'interactive', 'visualization', 'help', 'users', 'analyze', 'text', ',', 'create', 'insights']


### ✂️ Step 3: Stemming - Chopping words to their roots using PorterStemmer! ✂️

In [44]:
stemmer = PorterStemmer()
stemmed_tokens = [stemmer.stem(word) for word in filtered_tokens]
print("🔹 Stemmed tokens:", stemmed_tokens)

🔹 Stemmed tokens: ['featurelen', 'gener', 'visual', 'appli', 'text', 'mine', 'concept', 'frequent', 'word', ',', 'express', ',', 'close', 'itemset', 'n-gram', 'guid', 'discoveri', 'process', '.', 'concept', 'combin', 'interact', 'visual', 'help', 'user', 'analyz', 'text', ',', 'creat', 'insight']


### 🌱 Step 4: Lemmatization - Morphing words to their base form with WordNetLemmatizer! 🌱

In [45]:
def lemmatize_with_spacy(tokens):
    doc = nlp(' '.join(tokens))
    return [token.lemma_ for token in doc]

lemmatized_tokens = lemmatize_with_spacy(filtered_tokens)
print("🔹 Lemmatized tokens:", lemmatized_tokens)

🔹 Lemmatized tokens: ['FeatureLens', 'generate', 'visual', 'apply', 'text', 'mining', 'concept', 'frequent', 'word', ',', 'expression', ',', 'closed', 'itemset', 'n', '-', 'gram', 'guide', 'discovery', 'process', '.', 'concept', 'combine', 'interactive', 'visualization', 'help', 'user', 'analyze', 'text', ',', 'create', 'insight']


In [46]:
# lemmatizer = WordNetLemmatizer()
# lemmatized_tokens = [lemmatizer.lemmatize(word) for word in filtered_tokens]
# print("🔹 Lemmatized tokens:", lemmatized_tokens)

### 💼 Step 5: Vectorization - Turn those words into numbers for our model! 📊

#### 🧮 Count Vectorizer - Counting word occurrences

In [47]:
count_vectorizer = CountVectorizer()
count_vectors = count_vectorizer.fit_transform([' '.join(lemmatized_tokens)])
print("🔹 Count Vectorizer feature names:", count_vectorizer.get_feature_names_out())
print("🔹 Count Vectors:\n", count_vectors.toarray())

🔹 Count Vectorizer feature names: ['analyze' 'apply' 'closed' 'combine' 'concept' 'create' 'discovery'
 'expression' 'featurelens' 'frequent' 'generate' 'gram' 'guide' 'help'
 'insight' 'interactive' 'itemset' 'mining' 'process' 'text' 'user'
 'visual' 'visualization' 'word']
🔹 Count Vectors:
 [[1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1]]


#### 🔥 TF-IDF Vectorizer - Considering word frequency across documents

In [48]:
tfidf_vectorizer = TfidfVectorizer()
tfidf_vectors = tfidf_vectorizer.fit_transform([' '.join(lemmatized_tokens)])
print("🔹 TF-IDF Vectorizer feature names:", tfidf_vectorizer.get_feature_names_out())
print("🔹 TF-IDF Vectors:\n", tfidf_vectors.toarray())

🔹 TF-IDF Vectorizer feature names: ['analyze' 'apply' 'closed' 'combine' 'concept' 'create' 'discovery'
 'expression' 'featurelens' 'frequent' 'generate' 'gram' 'guide' 'help'
 'insight' 'interactive' 'itemset' 'mining' 'process' 'text' 'user'
 'visual' 'visualization' 'word']
🔹 TF-IDF Vectors:
 [[0.18257419 0.18257419 0.18257419 0.18257419 0.36514837 0.18257419
  0.18257419 0.18257419 0.18257419 0.18257419 0.18257419 0.18257419
  0.18257419 0.18257419 0.18257419 0.18257419 0.18257419 0.18257419
  0.18257419 0.36514837 0.18257419 0.18257419 0.18257419 0.18257419]]


#### 🎉 And that's it guys! Our text is now preprocessed and ready for some NLP magic! 🎉

# Part 2 : Basic NLP Tasks

####  🎉 Now, let's dive into some basic NLP tasks! 🎉

### 📢 Task 1: Sentiment Analysis - Get those text vibes! 😃😢😡

In [49]:
# NLTK's VADER for sentiment analysis
from nltk.sentiment.vader import SentimentIntensityAnalyzer

sid = SentimentIntensityAnalyzer()

sentiment_scores = sid.polarity_scores(text)
print("🔹 Sentiment Scores:", sentiment_scores)

def get_sentiment_label(scores):
    if scores['compound'] >= 0.05:
        return 'positive'
    elif scores['compound'] <= -0.05:
        return 'negative'
    else:
        return 'neutral'
    
sentiment_label = get_sentiment_label(sentiment_scores)
print(f"🔹 Sentiment Label: {sentiment_label}")

🔹 Sentiment Scores: {'neg': 0.0, 'neu': 0.879, 'pos': 0.121, 'compound': 0.5859}
🔹 Sentiment Label: positive


### 🎭 Task 2: Named Entity Recognition (NER) - Who's who and what's what? 🤔

In [50]:
# using spaCy
doc = nlp(text)

entities = [(entity.text, entity.label_) for entity in doc.ents]
print("🔹 Named Entities:", entities)

🔹 Named Entities: [('FeatureLens', 'ORG')]


### 🏷️ Task 3: Part-of-Speech Tagging - Tagging words like a pro! 🏷️

In [51]:
pos_tags = [(token.text, token.pos_) for token in doc]
print("🔹 Part-of-Speech Tags:", pos_tags)

🔹 Part-of-Speech Tags: [('\n', 'SPACE'), ('FeatureLens', 'PROPN'), ('generates', 'VERB'), ('visuals', 'NOUN'), ('by', 'ADP'), ('applying', 'VERB'), ('text', 'NOUN'), ('mining', 'NOUN'), ('concepts', 'NOUN'), ('such', 'ADJ'), ('as', 'ADP'), ('frequent', 'ADJ'), ('words', 'NOUN'), (',', 'PUNCT'), ('expressions', 'NOUN'), (',', 'PUNCT'), ('and', 'CCONJ'), ('closed', 'ADJ'), ('itemsets', 'NOUN'), ('of', 'ADP'), ('n', 'NOUN'), ('-', 'PUNCT'), ('grams', 'NOUN'), ('to', 'PART'), ('guide', 'VERB'), ('the', 'DET'), ('discovery', 'NOUN'), ('process', 'NOUN'), ('.', 'PUNCT'), ('These', 'DET'), ('concepts', 'NOUN'), ('are', 'AUX'), ('combined', 'VERB'), ('with', 'ADP'), ('interactive', 'ADJ'), ('visualization', 'NOUN'), ('to', 'PART'), ('help', 'VERB'), ('users', 'NOUN'), ('analyze', 'VERB'), ('text', 'NOUN'), (',', 'PUNCT'), ('create', 'VERB'), ('insights', 'NOUN'), ('\n', 'SPACE')]


### 📚 Task 4: Text Classification - Let's train a simple classifier! 📚

In [52]:
train_texts = [
    "I love sunny days",
    "I hate rainy days",
    "Sunshine makes me happy",
    "Rainy days make me sad"
]
train_labels = ['positive', 'negative', 'positive', 'negative']

#### 🧑‍🏫 Step 1: Vectorize the training texts

In [53]:
vectorizer = CountVectorizer()
X_train = vectorizer.fit_transform(train_texts)

#### 🧠 Step 2: Train a simple classifier (Naive Bayes)

In [54]:
from sklearn.naive_bayes import MultinomialNB

classifier = MultinomialNB()
classifier.fit(X_train, train_labels)

MultinomialNB()

#### 🎓 Step 3: Predict sentiment of a new text

In [55]:
new_text = "I feel happy when it is sunny"
X_new = vectorizer.transform([new_text])
predicted_label = classifier.predict(X_new)[0]
print(f"🔹 New Text: {new_text}")
print(f"🔹 Predicted Sentiment: {predicted_label}")

🔹 New Text: I feel happy when it is sunny
🔹 Predicted Sentiment: positive


#### 🎉 And that's a wrap on our basic NLP tasks! You're now an NLP hero! 🎉

# Part 3 : Advanced NLP Techniques

## Sub-part 1  : Word Embeddings (Word2Vec, GloVe) 🌐

####  🗣️ Word Embeddings are like word vibes! They capture semantic meaning by representing words as vectors.
#### 🚀 First up, let's explore Word2Vec using gensim! 🧠

In [56]:
import gensim
from gensim.models import Word2Vec

sentences = [
    "I love sunny days",
    "I hate rainy days",
    "Sunshine makes me happy",
    "Rainy days make me sad"
]

#### 🪄 Step 1: Tokenization (we did this before, but let's do it again for completeness)

In [57]:
tokenized_sentences = [word_tokenize(sentence.lower()) for sentence in sentences]
print("🔹 Tokenized Sentences:", tokenized_sentences)

🔹 Tokenized Sentences: [['i', 'love', 'sunny', 'days'], ['i', 'hate', 'rainy', 'days'], ['sunshine', 'makes', 'me', 'happy'], ['rainy', 'days', 'make', 'me', 'sad']]


#### 🧠 Step 2: Train the Word2Vec model

In [58]:
word2vec_model = Word2Vec(sentences=tokenized_sentences, vector_size=100, window=5, min_count=1, workers=4)
print("🔹 Word2Vec Model Trained!")

🔹 Word2Vec Model Trained!


#### 🔍 Step 3: Explore Word2Vec embeddings

In [59]:
word = "sunny"
if word in word2vec_model.wv:
    print(f"🔹 Vector for '{word}':", word2vec_model.wv[word])
else:
    print(f"🔹 Word '{word}' not in vocabulary")

🔹 Vector for 'sunny': [ 7.0887972e-03 -1.5679300e-03  7.9474989e-03 -9.4886590e-03
 -8.0294991e-03 -6.6403709e-03 -4.0034545e-03  4.9892161e-03
 -3.8135587e-03 -8.3199050e-03  8.4117772e-03 -3.7470020e-03
  8.6086961e-03 -4.8957514e-03  3.9185942e-03  4.9220170e-03
  2.3926091e-03 -2.8188038e-03  2.8491246e-03 -8.2562361e-03
 -2.7655398e-03 -2.5911583e-03  7.2490061e-03 -3.4634031e-03
 -6.5997029e-03  4.3404270e-03 -4.7448516e-04 -3.5975564e-03
  6.8824720e-03  3.8723124e-03 -3.9002013e-03  7.7188847e-04
  9.1435025e-03  7.7546560e-03  6.3618720e-03  4.6673026e-03
  2.3844899e-03 -1.8416261e-03 -6.3712932e-03 -3.0181051e-04
 -1.5653884e-03 -5.7228567e-04 -6.2628710e-03  7.4340473e-03
 -6.5914928e-03 -7.2392775e-03 -2.7571463e-03 -1.5154004e-03
 -7.6357173e-03  6.9824100e-04 -5.3261113e-03 -1.2755442e-03
 -7.3651113e-03  1.9605684e-03  3.2731986e-03 -2.3138524e-05
 -5.4483581e-03 -1.7260861e-03  7.0849168e-03  3.7362587e-03
 -8.8810492e-03 -3.4135508e-03  2.3541022e-03  2.1380198e-03
 -

#### 👯‍♂️ Find similar words

In [60]:
similar_words = word2vec_model.wv.most_similar(word, topn=5)
print(f"🔹 Words similar to '{word}':", similar_words)

🔹 Words similar to 'sunny': [('love', 0.10941850394010544), ('makes', 0.10889014601707458), ('days', 0.06285077333450317), ('happy', 0.05048205703496933), ('sunshine', 0.026806795969605446)]


#### 🌐 Now, let's explore GloVe embeddings with spaCy! 🧠
#### 📢 If you are testing this notebook, ,ake sure to download and test the larger spaCy model for better results:
#### python -m spacy download en_core_web_md

In [61]:
nlp_glove = spacy.load('en_core_web_md')

#### 🔍 Step 4: Explore GloVe embeddings

In [62]:
doc = nlp_glove("I love sunny days")
for token in doc:
    print(f"🔹 Token: {token.text}, Vector: {token.vector[:5]}...")  # Show first 5 dimensions for brevity

🔹 Token: I, Vector: [ -1.8607    0.15804  -4.1425   -8.6359  -16.955  ]...
🔹 Token: love, Vector: [ 2.0565  -3.2259  -5.7364  -6.146    0.15748]...
🔹 Token: sunny, Vector: [-0.14498  0.65651 -2.8764   0.40125 -1.0028 ]...
🔹 Token: days, Vector: [-3.0808  4.6691  1.1    -1.3048  4.1861]...


#### 👯‍♂️ Find similar words using spaCy's GloVe embeddings

In [63]:
def find_similar_words_spacy(word):
    token = nlp_glove.vocab[word]
    queries = [w for w in token.vocab if w.is_lower == token.is_lower and w.prob >= -15]
    by_similarity = sorted(queries, key=lambda w: token.similarity(w), reverse=True)
    return [w.text for w in by_similarity[:5]]

word = "sunny"
similar_words_glove = find_similar_words_spacy(word)
print(f"🔹 Words similar to '{word}' using GloVe:", similar_words_glove)

🔹 Words similar to 'sunny' using GloVe: []


#### 🎉 And that's a wrap on Word Embeddings! You're now a Word2Vec and GloVe pro! 🎉

## Sub-part 2 : Sequence Models (RNN, LSTM, GRU) 🌐

#### 🎉 Get ready to ride the wave of Sequence Models! 🌊

In [64]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, LSTM, GRU, Dense
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer
import numpy as np

2024-06-13 03:54:55.730968: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-06-13 03:54:55.731101: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-06-13 03:54:55.917712: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


In [65]:
# 🌟 Sample sentences for sequence modeling (replace with your dataset)
sentences = [
    "I love sunny days",
    "I hate rainy days",
    "Sunshine makes me happy",
    "Rainy days make me sad",
    "I feel great on sunny days",
    "Rainy days are gloomy and sad"
]

#### 🎯 Step 1: Tokenization and Padding

In [66]:
max_vocab_size = 1000
max_sequence_length = 10

# Tokenize the sentences
tokenizer = Tokenizer(num_words=max_vocab_size)
tokenizer.fit_on_texts(sentences)
sequences = tokenizer.texts_to_sequences(sentences)
word_index = tokenizer.word_index

# Pad the sequences
padded_sequences = pad_sequences(sequences, maxlen=max_sequence_length, padding='post')
print("🔹 Padded Sequences:\n", padded_sequences)


🔹 Padded Sequences:
 [[ 2  7  4  1  0  0  0  0  0  0]
 [ 2  8  3  1  0  0  0  0  0  0]
 [ 9 10  5 11  0  0  0  0  0  0]
 [ 3  1 12  5  6  0  0  0  0  0]
 [ 2 13 14 15  4  1  0  0  0  0]
 [ 3  1 16 17 18  6  0  0  0  0]]


#### 🎢 Step 2: Preparing the labels

In [67]:
labels = np.array([1, 0, 1, 0, 1, 0])  # Positive: 1, Negative: 0

#### 🚀 Step 3: Build and train a Simple RNN model

In [68]:
print("🚀 Training a Simple RNN model...")

rnn_model = Sequential([
    Embedding(input_dim=max_vocab_size, output_dim=32, input_length=max_sequence_length),
    SimpleRNN(32, return_sequences=False),
    Dense(1, activation='sigmoid')
])

rnn_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
rnn_model.summary()

# Train the RNN model
rnn_model.fit(padded_sequences, labels, epochs=5, verbose=2)

🚀 Training a Simple RNN model...


/opt/conda/lib/python3.10/site-packages/keras/src/layers/core/embedding.py:86: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/5
1/1 - 2s - 2s/step - accuracy: 0.3333 - loss: 0.7038
Epoch 2/5
1/1 - 0s - 26ms/step - accuracy: 0.6667 - loss: 0.6854
Epoch 3/5
1/1 - 0s - 26ms/step - accuracy: 1.0000 - loss: 0.6676
Epoch 4/5
1/1 - 0s - 26ms/step - accuracy: 1.0000 - loss: 0.6498
Epoch 5/5
1/1 - 0s - 27ms/step - accuracy: 1.0000 - loss: 0.6317


#### 🚀 Step 4: Build and train an LSTM model

In [69]:
print("🚀 Training an LSTM model...")

lstm_model = Sequential([
    Embedding(input_dim=max_vocab_size, output_dim=32, input_length=max_sequence_length),
    LSTM(32, return_sequences=False),
    Dense(1, activation='sigmoid')
])

lstm_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
lstm_model.summary()

# Train the LSTM model
lstm_model.fit(padded_sequences, labels, epochs=5, verbose=2)


🚀 Training an LSTM model...


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/5
1/1 - 2s - 2s/step - accuracy: 0.5000 - loss: 0.6931
Epoch 2/5
1/1 - 0s - 28ms/step - accuracy: 0.5000 - loss: 0.6926
Epoch 3/5
1/1 - 0s - 28ms/step - accuracy: 0.6667 - loss: 0.6921
Epoch 4/5
1/1 - 0s - 28ms/step - accuracy: 1.0000 - loss: 0.6915
Epoch 5/5
1/1 - 0s - 27ms/step - accuracy: 0.6667 - loss: 0.6910


#### 🚀 Step 5: Build and train a GRU model

In [70]:
print("🚀 Training a GRU model...")

gru_model = Sequential([
    Embedding(input_dim=max_vocab_size, output_dim=32, input_length=max_sequence_length),
    GRU(32, return_sequences=False),
    Dense(1, activation='sigmoid')
])

gru_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
gru_model.summary()

gru_model.fit(padded_sequences, labels, epochs=5, verbose=2)

🚀 Training a GRU model...


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru (GRU)                       │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/5
1/1 - 3s - 3s/step - accuracy: 0.5000 - loss: 0.6930
Epoch 2/5
1/1 - 0s - 29ms/step - accuracy: 0.5000 - loss: 0.6928
Epoch 3/5
1/1 - 0s - 59ms/step - accuracy: 0.5000 - loss: 0.6925
Epoch 4/5
1/1 - 0s - 28ms/step - accuracy: 0.8333 - loss: 0.6923
Epoch 5/5
1/1 - 0s - 28ms/step - accuracy: 0.6667 - loss: 0.6920


#### 🎉 Comparing Model Performances

In [71]:
# Evaluate the models
rnn_loss, rnn_accuracy = rnn_model.evaluate(padded_sequences, labels, verbose=0)
lstm_loss, lstm_accuracy = lstm_model.evaluate(padded_sequences, labels, verbose=0)
gru_loss, gru_accuracy = gru_model.evaluate(padded_sequences, labels, verbose=0)

print(f"🔹 RNN Model Accuracy: {rnn_accuracy:.2f}")
print(f"🔹 LSTM Model Accuracy: {lstm_accuracy:.2f}")
print(f"🔹 GRU Model Accuracy: {gru_accuracy:.2f}")

🔹 RNN Model Accuracy: 1.00
🔹 LSTM Model Accuracy: 0.67
🔹 GRU Model Accuracy: 0.67


#### 🎉 And that's a wrap on Sequence Models! You're now an RNN, LSTM, and GRU pro! 🎉